# all packages and jquery/bootstrap assumed installed by iiab install

- name: Create js-menu directory tree and dummy module
  file: path={{ item }}
        mode=0755
        owner=root
        group=root
        state=directory
  with_items:
    - "{{ js_menu_dir }}"
    - "{{ js_menu_dir }}menu-files"
    - "{{ js_menu_dir }}sample-menus"
    - "{{ doc_root }}/modules/en-test_mod"

- name: Copy a dummy module for oob menu
  copy: src=en-test_mod/index.html
        dest="{{ doc_root }}/modules/en-test_mod"
        owner=root
        group=root
        mode=0644
        force=no

# need to merge locally edited menu-defs
# continue to use cp-menu until we have forms-based menu-def editing
#- name: Synchronize/Copy menu-files
#  synchronize:
#    src: files/menu-files
#    dest: "{{ js_menu_dir }}/menu-files"

- name: Synchronize/Copy menu-files
  synchronize:
    src: files/sample-menus
    dest: "{{ js_menu_dir }}/sample-menus"

- name: Install js-menu config file
  template: src=config.json.j2
            dest={{ js_menu_dir }}/config.json
            owner=root
            group=root
            mode=0644

- name: Install index.html in home
  copy: src=index.html
        dest="{{ doc_root }}/home/index.html"
        owner=root
        group=root
        mode=0644

- name: Install menu.json in home
  copy: src=menu.json
        dest="{{ doc_root }}/home/menu.json"
        owner=root
        group=root
        mode=0644
        force=no


###########
sample
- name: Download substitute software for i386 on FC18 XO1.5
  get_url:
    url: "{{ iiab_download_url }}/{{ item }}"
    dest: "{{ downloads_dir }}/{{ item }}"
    timeout: "{{ download_timeout }}"
  with_items:
    - hostapd_8188_i386
  when: wifi_id == "tplink_WM725M" and xo_model == "XO-1.5" and internet_available
  tags:
    - xo

- name: Put the substitute in place
  copy:
    src: "{{ downloads_dir }}/hostapd_8188_i386"
    dest: /usr/sbin/hostapd
    backup: yes
    mode: 0775
    owner: root
    group: root
  when: wifi_id == "tplink_WM725M" and xo_model == "XO-1.5"

OR

- name: Download & unzip 20MB http://download.iiab.io/packages/mongodb_stretch_3_0_14_core.zip to /tmp/mongodb-3.0.1x (rpi)
  unarchive:
    remote_src: yes
    src: "{{ iiab_download_url }}/mongodb_stretch_3_0_14_core.zip"
    dest: /tmp/mongodb-3.0.1x
  when: internet_available and is_rpi

- name: Install (move) its 3 CORE binaries from /tmp/mongodb-3.0.1x/core to /usr/bin (rpi)
  shell: mv /tmp/mongodb-3.0.1x/core/* /usr/bin
  when: internet_available and is_rpi

- name: Download & unzip 15MB http://download.iiab.io/packages/mongodb_stretch_3_0_14_tools.zip [IN FACT THIS ONE'S 3.0.15] to /tmp/mongodb-3.0.1x (rpi)
  unarchive:
    remote_src: yes
    src: "{{ iiab_download_url }}/mongodb_stretch_3_0_14_tools.zip"
    dest: /tmp/mongodb-3.0.1x
  when: internet_available and is_rpi

################


- name: Copy Menu Files and Create Feedback Database
  shell: ./cp-menus

- name: Make web server user owner of images after copying
  file: path="{{ js_menu_dir }}menu-files/images/"
        mode=0755
        owner="{{ apache_user }}"
        group="{{ apache_user }}"
        state=directory
        recurse=true

- name: Add any IIAB roles that are installed to home/menu.js
  shell: "{{ cmdsrv_dir }}/scripts/iiab_update_menus.py"

# Enable or Disable menu client setting server time
- name: Give {{ apache_user }} permission to set time
  template:
    src: 021_apache_set_time.j2
    dest: /etc/sudoers.d/021_apache_set_time
    mode: 0644
  when: apache_allow_sudo

- name: Remove above
  file:
    path: /etc/sudoers.d/021_apache_set_time
    state: absent
  when: not apache_allow_sudo

# For Osm Vector Maps
# If not enabled install empty files
# Otherwise run /usr/bin/iiab-update-map

- name: Copy Osm Vector Maps dummy files
  copy:
    src: map/{{ item }}
    dest: "{{ doc_root }}/common/assets/{{ item }}"
    owner: root
    group: root
    mode: 0644
    force: yes

  with_items:
    - regions.json
    - vector-map-idx.json
  when: not osm_vector_maps_enabled

- name: Remove region.json dummy file if osm_vector_maps_enabled
  file:
    path: "{{ doc_root }}/common/assets/regions.json"
    state: absent
  when: osm_vector_maps_enabled

- name: Create a link to osm catalog in /common/assets
  file:
    src: "{{ vector_map_path }}/maplist/assets/regions.json"
    dest: "{{ doc_root }}/common/assets/regions.json"
    state: link
  when: osm_vector_maps_enabled

- name: Add any MAPS that are installed to home/menu.js
  shell: /usr/bin/iiab-update-map
  when: osm_vector_maps_enabled
